- type: faction
  name: "Mandato Solar Divino"
  id: DSM
  descriptionPrefix: |
    Mandato Solar Divino
    TEMPO DE JOGO PRÉVIO RECOMENDADO: NENHUM
    Um dos grandes poderes no Setor Taipan.
    Bom para novos jogadores e representa a experiência de Hullrot em seu príncipio.
  buttonColor: DarkSlateBlue
  description: |
    Controlando muito do espaço conhecido fora do Crescente, o Mandato Solar Divino, ou simplesmente
    'O Império' para os leigos, é um produto da miséria dos sistemas centrais pós-colapso interestelar
    com uma rápida expansão imperialista, que logo iria se estabilizar em um sistema feudal,
    governado pelo mistificado e supostamente todo poderoso 'Kaiser' do sistema Prime dentro
    do setor do Núcleo Imperial, antigamente conhecido pelo registro imperial como Sol e Pisces,
    respectivamente. Após a rebelião da LTNC (NCWL), no Crescente, O Império se encontrou enfraquecido,
    mas um contra-ataque bem sucedido conseguiu recuperar a fortaleza estelar de Kal Surezai
    e abriu o caminho para o retorno Imperial ao sistema, embora o controle nas periferias de Taipan
    ainda é disputado, batalhas e atos de terror são comuns.

    Sendo efetivamente a principal superpotência de toda a humanidade, O Império permite um grau
    liberdade econõmica para seus subordinados e promove lealdade de um jeito não tão diferente das
    megacorporações da Antiga Terra, com aspirantes subindo a escada nobre de diferentes casas ou
    guildas, como a Casa de Olywir do sistema de Domínio. Fidalgos tentando se manifestar contra
    o regime rápidamente são detidos e desaparecem misteriosamente. Controle de informação firme
    e reescrição histórica funcionam para servir as vontades do Império.
    
    Espécies não-humanas são permitidas em algumas posições prestigiosas mas são sujeitas a julgamento
    intensivo de seus superiores e discriminação formal e não-formal.
  color: "#9FED58"
  weight: 8
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: dsm

- type: faction
  name: "Liga dos Trabalhadores da Nova Crescente"
  id: NCWL
  descriptionPrefix: |
    Liga dos Trabalhadores da Nova Crescente
    TEMPO DE JOGO PRÉVIO RECOMENDADO: NENHUM
    Um dos grandes poderes no Setor Taipan.
    Bom para novos jogadores e representa a experiência de Hullrot em seu príncipio.
  buttonColor: "#a46106"
  description: |
    Stitched together from the still-warm corpses of many labor unions that were in disorganized rebellion
    against Imperial forces in the Feudal Era before the collapse of Bluespace lanes leading in and out of the
    Sector, the NCWL are the undisputed victors of the Crescent Revolution, holding four out of six systems
    within the Sector and ruling from their seat of power in the Core. Holding socialist ideals at heart, the
    NCWL aims to build a government by laborers, and for the people. Recently having launched a liberation campaign
    against the Taypan system in the Outer Rim, the League are finally throwing their hats in the pile to make
    their bid for the untamed frontier.
  color: "#9FED58"
  weight: 7
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: ncwl

- type: faction
  name: "Shinohara Heavy Industries"
  id: SHI
  descriptionPrefix: |
    Shinohara Heavy Industries
    TEMPO DE JOGO PRÉVIO RECOMENDADO: 3 HORAS / 1 ROUND
    An industrial giant, with trade-heavy gameplay and high tech.
    Expect heavy profit quotas, pirate raids and little support.
  buttonColor: DarkSlateGray
  description: |
    Currently the holder of many patents and technologies from the now-defunct NanoTrasen Industries, SHI is the
    unmatched and unrivaled corporate powerhouse in the Sector. Fingers in every pie, they manage logistics
    between systems, development of new technologies, mining operations, and even dabble in the manufacturing of
    space-capable vessels. Sharing the system with the Syndicate, they have made their headquarters in Taypan,
    enjoying access to ore-rich asteroid veins.
  color: "#9FED58"
  weight: 6
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: shi

- type: faction
  name: "Coalizão das Estações Livres Taipenhas"
  id: TFSC
  descriptionPrefix: |
    Coalizão das Estações Livres Taipenhas
    TEMPO DE JOGO PRÉVIO RECOMENDADO: 3 HORAS / 1 ROUND
    Four individual corporations united under one flag, for profit and freedom.
    Other factions may offer contracts or ask for your services.
    Other factions may be suspicious or immediately hostile.
    Your allies may betray you for a higher paycheck.
  buttonColor: DarkRed
  description: |
    A conglomerate of pirate gangs, shipbreakers, and unsavory PMC groups, the Syndicate was formed shortly
    after the initial arrival of the Empire into the Sector, disembodied station gangs and pirate reavers at
    first, and slowly growing to be a regional superpower under the leadership of Imperial nobility and deserter
    Ser William 'Pincer' Moore. They've made Taypan their headquarters, thriving within the lawless frontier, away
    from the overreaching grasp of the NCWL and reasonably far enough from the Empire's remnants still roaming
    the Sector.
  color: "#9FED58"
  weight: 5
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tfsc

- type: faction
  name: "The Taypani-Atyrian Pact"
  id: TAP
  descriptionPrefix: |
    MINIMUM PLAYTIME: 10 HOURS / 3 ROUNDS
    This faction has only a very small outpost in the Taypan system.
    A small, hidden station with only four roles is their only presence.
    Play at your own risk.
  buttonColor: DarkGreen
  description: |
    A loosely organized tribal community of nomadic starfarers, the Taypani-Atyrian Pact consists of several nomadic
    families of various racial backgrounds. Primarily made up of the spiritual Arabet, the militaristic Al'Seik,
    the materialistic Izdari, and the scrappy Thukker families, they operate out of a converted capital freighter,
    moving from site to site to eke out a living. Most nomads carry the foul reputations of mercenaries, lowlives,
    smugglers, racketeers, and gamblers.
  color: "#9FED58"
  weight: 4
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: fourfamilies

- type: faction
  name: "Saint Romaine's Militia"
  id: SRM
  descriptionPrefix: |
    MINIMUM PLAYTIME: 10 HOURS / 3 ROUNDS
    This faction is only very rarely present in the Taypan system.
    Restricted to Special Midround Spawns
  buttonColor: Black
  description: |
    Formerly several fireteams of the Imperial Compliance Corps united under a single wing, the SRM have
    found their new identity in the reclamation of escaped Imperial 'assets', as well as the 'conscription'
    of new ones. Essentially a slaver's guild with a self-appointed divine edge, they operate out of the
    Domain system under their Imperial overlords, but often stray into Taypan to capture victims for
    the rebuilding effort.
  color: "#9FED58"
  weight: 3
  enabled: false
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: srm

- type: faction
  name: "Central Sol Authority"
  id: ATH
  descriptionPrefix: |
    MINIMUM PLAYTIME: 10 HOURS / 3 ROUNDS
    This faction is only very rarely present in the Taypan system.
    Restricted to Special Midround Spawns
  buttonColor: Black
  description: |
    The victors of an undisputed internal war that broke out in Sol over the Kaiser's turbulent and
    violent reign, the Authority was born out of a need for reform. Lead by the Jovian ideals of
    psionic purity, the Central Sol Authority has minimal interest in feudal reign like their precursors,
    instead focusing on violent conquests made with the purpose of eradicating species and communities
    that they've found to be linked to the Boundary, Taypan, and other psionic phenomena. It is believed
    by Authority officials that the source of the Boundary itself comes from the combined, manifested
    thought of all psionically-enabled people in the Imperial Supercluster, and with every spell cast,
    every psionicist born, it only becomes larger and more aggressive.

    Effectively the prime superpower of all of humanity, the Authority allows for a good amount of
    economic freedom for its non-psionicists and promotes loyalty in a manner not too dissimilar to
    the megacorporations of old Earth, with aspiring members climbing up the military ladder of
    different militias, such as the 43rd Battlegroup of the Sol system. Forschers thinking that they
    can speak up against the current regime quickly find themselves screened against and detained,
    however, with tight information control preventing widespread dissent and often rewriting history
    itself to suit the needs of the Authority.
  color: "#ffffed"
  weight: 2
  enabled: false
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: csa
   

- type: faction
  name: "Colonial Minutemen"
  id: TSP
  description: |
    Appointed by themselves as a civil enforcement agency, the Colonial Minutemen are a frontier sheriff agency
    run solely on scant funding from confiscated items and donations from private and civilian entities.
    Formed with the system's best interests at heart, underperforming equipment, underfunded staff, and
    tendency to draw their members from within impoverished circles leave them susceptible to corruption - which
    the major powers of the system often has little manpower or resources to mitigate or mend.
  color: "#9FED58"
  weight: 1
  enabled: false
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tsp
